import torch
import torch.nn as nn
from engine.config.schema import ModelConfig, AttentionConfig
from engine.components.attention.sliding import SlidingWindowAttention
from engine.components.positional import PEOutput


def test_sliding_window_causality():
    """
    Verifies that tokens can only attend within the window_size in SlidingWindowAttention.
    """
    hidden_size = 64
    num_heads = 4
    window_size = 4
    seq_len = 16

    cfg = ModelConfig(
        hidden_size=hidden_size,
        attention=AttentionConfig(
            type="sliding",
            num_heads=num_heads,
            num_kv_heads=num_heads,
            window_size=window_size,
        ),
    )

    attn = SlidingWindowAttention(cfg)
    attn.eval()

    x = torch.randn(1, seq_len, hidden_size)
    pe_out = PEOutput()  # Empty PEOutput

    # We want to inspect attention weights.
    # SDPA doesn't expose them easily, so we use a mock-up or check logic.
    # A better way is to verify that for a specific token i, only j in [i-window+1, i] are seen.

    # Let's override SDPA with a manual implementation to verify the mask.
    # Or just verify that the mask generated by the model is correct.
    from engine.models.decoder import DecoderModel

    model = DecoderModel(cfg)
    model.eval()

    # Generate the mask
    mask = model._get_sliding_window_mask(
        seq_len, seq_len, window_size, x.device, x.dtype
    )

    # mask is (seq_len, seq_len)
    for i in range(seq_len):
        for j in range(seq_len):
            if j > i or j <= i - window_size:
                assert mask[i, j] == torch.finfo(x.dtype).min / 2, (
                    f"Token {i} should NOT see {j}"
                )
            else:
                assert mask[i, j] == 0.0, f"Token {i} SHOULD see {j}"


if __name__ == "__main__":
    test_sliding_window_causality()
